version: "3.9"
services:
  #Mysql container
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'grupo16'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - red-db
  #Servidores escritos en flask
  server:
    build: ./
    restart: always
    command: python app.py
    expose:
      - "3000"    
    volumes:
      - ./src:/python-flask
    environment:
      - SEVER_NAME=201404006_
    networks:
      - red-servidores
      - red-db

volumes:
  my-db:
networks:
  red-servidores:
    driver: bridge
    ipam:
     config:
       - subnet: 172.35.76.0/24
  red-db:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.16.0/24 