version: "3.9"
services:
  #Mysql container
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'grupo16'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    networks:
      - red-db
  #Servidores escritos en flask
  server:
    build: ./
    image: pruebas-server
    restart: always
    command: python app.py
    expose:
      - "3500"
    volumes:
      - ./src:/python-flask
    environment:
      - SEVER_NAME=201404006_
    networks:
      - red-servidores
      - red-db

networks:
  red-servidores:
    driver: bridge
  red-db:
    driver: bridge